// app/layout.tsx or _app.tsx
import type { Metadata } from "next";
import { Inter, Fjalla_One, Oswald,Bebas_Neue,Anton,Inter_Tight,Prata ,Staatliches} from "next/font/google";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs';
import { CartProvider } from '@/app/context/CartContext';
import "./globals.css";
import { Toaster } from "react-hot-toast";

const oswald = Oswald({
  subsets: ["latin"],
  weight: ['500', '700'],
});
const bebas = Bebas_Neue({
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "FARM TO MARKET",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <CartProvider>
      

        <html lang="en">
       
          <body className={bebas.className}>
            {children}
            <Toaster/>

          </body>
          
        </html>
        
       
      </CartProvider>
    </ClerkProvider>
  );
}
