import type { Metadata } from "next";
import { Inter,Fjalla_One,Oswald } from "next/font/google";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'

import "./globals.css";

const oswald = Oswald({
  subsets: ["latin"],
 
});

export const metadata: Metadata = {
  title: "FARM TO MARKET",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={oswald.className}>{children}</body>
    </html>
    </ClerkProvider>
  );
}
