// app/layout.tsx or _app.tsx
import type { Metadata } from "next";
import { Inter, Fjalla_One, Oswald } from "next/font/google";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs';
import { CartProvider } from '@/app/context/CartContext';
import "./globals.css";

const oswald = Oswald({
  subsets: ["latin"],
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: "FARM TO MARKET",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <CartProvider>
        <html lang="en">
          <body className={oswald.className}>{children}</body>
        </html>
      </CartProvider>
    </ClerkProvider>
  );
}
